Repository umc-8th-Channeling/FE, pull requests merged in 2025-07, with the labels that each got.

#27 [DOCS] README.md 업데이트
  README.md
Labels: 📑Docs

#28 [DEV] 앱 타이틀, 파비콘, 메타 정보 업데이트
  frontend/index.html
  frontend/public/icons/channeling.svg
Labels: 🤗Feature

#38 [DEV] textarea 모달 공용 컴포넌트 리팩토링
  frontend/src/components/ArrowButton.tsx
  frontend/src/components/Textarea.tsx
  frontend/src/components/TextareaWithArrow.tsx
Labels: 🛠️Refactor

#37 [DEV] Modal 컴포넌트 유연성 확보 및 스크롤 금지 삭제
  frontend/src/components/Modal.tsx
Labels: 🛠️Refactor

#40 [DEV] 레포트 페이지 중 그래프 제외 개요 탭, 아이디어 탭 UI 구현
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/assets/icons/bookmark.svg
  frontend/src/assets/icons/bookmark_active.svg
  frontend/src/assets/icons/refresh_2.svg
  frontend/src/assets/icons/up.svg
  frontend/src/components/Tabs.tsx
  frontend/src/components/chart/DoughnutChart.tsx
  frontend/src/components/chart/index.ts
  frontend/src/global.css
  frontend/src/pages/main/_components/VideoCard.tsx
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/_components/GuestModal.tsx
  frontend/src/pages/report/_components/Tag.tsx
  frontend/src/pages/report/_components/TitledSection.tsx
  frontend/src/pages/report/_components/VideoSummary.tsx
  frontend/src/pages/report/_components/analysis/TabAnalysis.tsx
  frontend/src/pages/report/_components/analysis/index.ts
  frontend/src/pages/report/_components/idea/NextContentsIdea.tsx
  frontend/src/pages/report/_components/idea/TabIdea.tsx
  frontend/src/pages/report/_components/idea/TrendKeywords.tsx
  frontend/src/pages/report/_components/idea/index.ts
  frontend/src/pages/report/_components/index.ts
  frontend/src/pages/report/_components/overview/CommentFeedback.tsx
  frontend/src/pages/report/_components/overview/Evaluation.tsx
  frontend/src/pages/report/_components/overview/Summary.tsx
  frontend/src/pages/report/_components/overview/TabOverview.tsx
  frontend/src/pages/report/_components/overview/index.ts
  frontend/src/pages/report/dummy.ts
  frontend/src/styles/scrollbar.css
  frontend/src/utils/format.ts
Labels: 🤗Feature

#48 [DEV] statCard 유틸 생성 및 적용
  frontend/src/pages/my/MyPage.tsx
Labels: 🤗Feature

#61 [DEV] 리포트 분석 페이지 UI 작업
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/pages/report/_components/analysis/AlgorithmOptimization.tsx
  frontend/src/pages/report/_components/analysis/TabAnalysis.tsx
  frontend/src/pages/report/_components/analysis/ViewerExitAnalysis.tsx
  frontend/src/pages/report/dummy.ts
Labels: 🤗Feature

#68 [DEV] 리포트 페이지 반응형 구현 및 코드 리팩토링
  frontend/src/components/Tabs.tsx
  frontend/src/components/chart/DoughnutChart.tsx
  frontend/src/components/chart/iconPlugin.ts
  frontend/src/components/chart/tooltipPlugin.ts
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/_components/GuestModal.tsx
  frontend/src/pages/report/_components/TitledSection.tsx
  frontend/src/pages/report/_components/UpdateModal.tsx
  frontend/src/pages/report/_components/VideoSummary.tsx
  frontend/src/pages/report/_components/analysis/index.ts
  frontend/src/pages/report/_components/idea/ContentsIdea.tsx
  frontend/src/pages/report/_components/idea/TabIdea.tsx
  frontend/src/pages/report/_components/idea/TrendKeywords.tsx
  frontend/src/pages/report/_components/idea/index.ts
  frontend/src/pages/report/_components/index.ts
  frontend/src/pages/report/_components/overview/CommentFeedback.tsx
  frontend/src/pages/report/_components/overview/Evaluation.tsx
  frontend/src/pages/report/_components/overview/Summary.tsx
  frontend/src/pages/report/_components/overview/TabOverview.tsx
  frontend/src/pages/report/_components/overview/index.ts
  frontend/src/pages/report/dummy.ts
Labels: 🤗Feature, 🛠️Refactor

#73 [DEV] 메인 페이지 화면 설계서에 맞춰 기능 보완
  frontend/src/components/ScrollToTop.tsx
  frontend/src/components/common/Navbar/NavbarDesktop.tsx
  frontend/src/pages/layouts/RootLayout.tsx
  frontend/src/pages/main/MainPage.tsx
  frontend/src/pages/main/_components/UrlInputForm.tsx
  frontend/src/pages/main/_components/UrlInputModal.tsx
  frontend/src/pages/main/_components/VideoCard.tsx
  frontend/src/pages/main/dummy.ts
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/dummy.ts
  frontend/src/router/router.tsx
  frontend/src/stores/authStore.ts
Labels: 🤗Feature

#80 [FIX] 리포트 페이지 분석 탭 텍스트 스타일링 수정
  frontend/src/global.css
  frontend/src/pages/report/_components/analysis/AlgorithmOptimization.tsx
  frontend/src/pages/report/_components/analysis/ViewerExitAnalysis.tsx
Labels: 🤗Feature, 🛠️Refactor

#84 [DEV] 저장소 card 삭제 기능 추가
  frontend/src/pages/library/LibraryPage.tsx
  frontend/src/pages/library/_components/RecentReportCard.tsx
  frontend/src/pages/library/_components/RecentReportShortsCard.tsx
  frontend/src/pages/library/_components/ScrapCard.tsx
Labels: 🤗Feature

#89 [DEV] 리포트 페이지 아이디어 카드 글자 수 제한 추가
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/_components/VideoSummary.tsx
  frontend/src/pages/report/_components/idea/ContentsIdea.tsx
  frontend/src/pages/report/_components/idea/TabIdea.tsx
  frontend/src/pages/report/_components/overview/CommentFeedback.tsx
  frontend/src/pages/report/dummy.ts
  frontend/src/types/report.ts
Labels: 🤗Feature

#88 [DEV] 페이지네이션 구현
  frontend/src/assets/icons/chevron_left.svg
  frontend/src/assets/icons/chevron_right.svg
  frontend/src/components/Pagination.tsx
  frontend/src/pages/my/_components/myReportModal.tsx
  frontend/src/pages/my/_components/myShortsCard.tsx
  frontend/src/pages/my/_components/myVideoCard.tsx
  frontend/src/pages/my/_components/videolist.tsx
  frontend/src/pages/my/dummy.ts
  frontend/src/types/profile.ts
Labels: ✨Feature

#91 [DEV] 모달 공용 컴포넌트 사이즈 변환 방식 수정
  .gitignore
  frontend/src/components/Modal.tsx
  frontend/src/components/Textarea.tsx
  frontend/src/hooks/useWindowWidth.ts
  frontend/src/pages/auth/_components/ChannelConceptModal.tsx
  frontend/src/pages/auth/_components/ViewerModal.tsx
Labels: ✨Feature, 🐛Bug

#99 [FIX] 내채널 페이지 lint 오류 수정
  frontend/src/components/Pagination.tsx
  frontend/src/pages/my/_components/myReportModal.tsx
  frontend/src/pages/my/_components/myShortsCard.tsx
  frontend/src/pages/my/_components/myVideoCard.tsx
Labels: 🐛Bug

#70 [DEV] 설정 페이지 작업
  frontend/src/assets/icons/camera.svg
  frontend/src/assets/icons/complete_off.svg
  frontend/src/assets/icons/complete_on.svg
  frontend/src/assets/icons/correction.svg
  frontend/src/assets/icons/edit.svg
  frontend/src/assets/icons/logout.svg
  frontend/src/assets/icons/send.svg
  frontend/src/assets/icons/toggle_off.svg
  frontend/src/assets/icons/toggle_on.svg
  frontend/src/assets/icons/write.svg
  frontend/src/components/CustomToggle.tsx
  frontend/src/components/EditButton.tsx
  frontend/src/components/common/Navbar/NavbarDesktop.tsx
  frontend/src/components/common/Navbar/NavbarLinksList.tsx
  frontend/src/components/common/Navbar/NavbarMobile.tsx
  frontend/src/components/common/Navbar/NavbarTablet.tsx
  frontend/src/components/common/Navbar/NavbarUserInfo.tsx
  frontend/src/hooks/main/useIsMobile.ts
  frontend/src/pages/layouts/RootLayout.tsx
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/pages/setting/_components/CloseButton.tsx
  frontend/src/pages/setting/_components/ConsentTab.tsx
  frontend/src/pages/setting/_components/OpenSettingPage.ts
  frontend/src/pages/setting/_components/ProfileTab.tsx
  frontend/src/pages/setting/_components/SettingButton.tsx
  frontend/src/pages/setting/_components/SettingInput.tsx
  frontend/src/pages/setting/_components/SettingLabel.tsx
  frontend/src/pages/setting/_components/SettingModalContainer.tsx
  frontend/src/pages/setting/_components/SettingPageRoute.tsx
  frontend/src/pages/setting/_components/SettingToggle.tsx
  frontend/src/pages/setting/_components/WithdrawlModal.tsx
  frontend/src/router/router.tsx
  frontend/src/stores/SettingStore.ts
Labels: ✨Feature
