Repository umc-8th-Channeling/FE, pull requests merged in 2025-08, with the labels that each got.

#109 [DEV] 저장소 페이지 페이지네이션 및 컴포넌트 구조 리팩토링
  frontend/src/pages/auth/_components/LoginModal.tsx
  frontend/src/pages/library/LibraryPage.tsx
  frontend/src/pages/library/_components/IdeaCard.tsx
  frontend/src/pages/library/_components/IdeaTab.tsx
  frontend/src/pages/library/_components/ReportTab.tsx
  frontend/src/pages/library/dummy.ts
  frontend/src/types/library.ts
Labels: ♻️Refactor

#105 [DEV] 구글 로그인 및 target,concept API 연결
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/api/axios.ts
  frontend/src/api/channel.ts
  frontend/src/constants/key.ts
  frontend/src/hooks/channel/useUpdateIdentity.ts
  frontend/src/hooks/useLocalStorage.ts
  frontend/src/pages/auth/GoogleRedirectPage.tsx
  frontend/src/pages/auth/NavbarModalsContainer.tsx
  frontend/src/pages/auth/_components/LoginModal.tsx
  frontend/src/router/router.tsx
  frontend/src/stores/LoginStore.ts
  frontend/src/stores/authStore.ts
  frontend/src/types/channel.ts
  frontend/vite.config.ts
Labels: ✨Feature

#120 [FIX] 저장소 페이지네이션 위치 오류를 수정
  frontend/src/pages/library/_components/IdeaTab.tsx
  frontend/src/pages/library/_components/ReportTab.tsx
Labels: ✨Feature

#128 [FIX] 구글 로그인 후 새로고침 시 유저 상태 초기화 문제 해결 및 로직 개선
  frontend/src/api/channel.ts
  frontend/src/components/common/Navbar/NavbarLinksList.tsx
  frontend/src/components/common/Navbar/NavbarUserInfo.tsx
  frontend/src/components/common/Navbar/dummy.ts
  frontend/src/constants/key.ts
  frontend/src/hooks/channel/useFetchAndSetUser.ts
  frontend/src/pages/auth/GoogleRedirectPage.tsx
  frontend/src/pages/layouts/RootLayout.tsx
  frontend/src/stores/authStore.ts
  frontend/src/types/channel.ts
  frontend/src/types/common.ts
Labels: ♻️Refactor, 🐛Bug

#136 [DEV] 로그아웃 기능 구현
  frontend/src/hooks/useLogout.ts
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/stores/authStore.ts
Labels: ✨Feature

#111 [DEV] 내 채널 페이지 API 연결
  frontend/src/api/channel.ts
  frontend/src/api/my.ts
  frontend/src/components/Pagination.tsx
  frontend/src/components/Skeleton.tsx
  frontend/src/hooks/my/useGetChannel.ts
  frontend/src/hooks/my/useGetChannelVideo.ts
  frontend/src/hooks/useThrottle.ts
  frontend/src/lib/mappers/profile/mapResponseToConcept.ts
  frontend/src/lib/mappers/profile/mapResponseToProfile.ts
  frontend/src/lib/mappers/profile/mapResponseToTargetbox.ts
  frontend/src/lib/mappers/profile/mapResponseToVideo.ts
  frontend/src/lib/mappers/profile/mapResponsetoStatCard.ts
  frontend/src/pages/auth/GoogleRedirectPage.tsx
  frontend/src/pages/my/MyPage.tsx
  frontend/src/pages/my/_components/Skeleton.tsx
  frontend/src/pages/my/_components/Skeleton/ConceptboxSkeleton.tsx
  frontend/src/pages/my/_components/Skeleton/ProfileSkeleton.tsx
  frontend/src/pages/my/_components/Skeleton/TargetboxSkeleton.tsx
  frontend/src/pages/my/_components/Skeleton/VideoSkeleton.tsx
  frontend/src/pages/my/_components/conceptbox.tsx
  frontend/src/pages/my/_components/myShortsCard.tsx
  frontend/src/pages/my/_components/profileCard.tsx
  frontend/src/pages/my/_components/targetbox.tsx
  frontend/src/pages/my/_components/videolist.tsx
  frontend/src/types/profile.ts
Labels: ✨Feature

#140 [DEV] 설정 모달 API 연동 작업
  frontend/.gitignore
  frontend/package.json
  frontend/src/api/user.ts
  frontend/src/components/common/Navbar/NavbarLinksList.tsx
  frontend/src/components/common/Navbar/NavbarMobile.tsx
  frontend/src/components/common/Navbar/NavbarTablet.tsx
  frontend/src/components/common/Navbar/NavbarUserInfo.tsx
  frontend/src/hooks/mutations/userMutations.ts
  frontend/src/hooks/queries/fetchMyProfile.ts
  frontend/src/pages/auth/_components/LoginModal.tsx
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/pages/setting/_components/OpenSettingPage.ts
  frontend/src/pages/setting/_components/ProfileImage.tsx
  frontend/src/pages/setting/_components/ProfileTab.tsx
  frontend/src/pages/setting/_components/SettingButton.tsx
  frontend/src/pages/setting/_components/SettingPageRoute.tsx
  frontend/src/stores/authStore.ts
  frontend/src/stores/consentStore.ts
  frontend/src/stores/profileImageStore.ts
  frontend/src/stores/snsFormStore.ts
  frontend/src/types/channel.ts
  frontend/src/types/user.ts
Labels: ✨Feature

#147 [DEV] 최초 로그인 과정에서 targets,concepts의 글자 제한 기능 추가
  frontend/src/components/Textarea.tsx
  frontend/src/components/TextareaWithArrow.tsx
  frontend/src/hooks/channel/useFetchAndSetUser.ts
  frontend/src/pages/auth/NavbarModalsContainer.tsx
  frontend/src/pages/auth/_components/ChannelConceptModal.tsx
  frontend/src/pages/auth/_components/ViewerModal.tsx
Labels: ✨Feature, 🐛Bug

#149 [DEV] 리포트 페이지 API 연동 및 화면 플로우 검증
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/App.tsx
  frontend/src/api/axios.ts
  frontend/src/api/main.ts
  frontend/src/api/report.ts
  frontend/src/components/chart/DoughnutChart.tsx
  frontend/src/hooks/main/useGetRecommendedVideo.ts
  frontend/src/hooks/main/useUrlInput.ts
  frontend/src/hooks/report/useGetReportAnalysis.ts
  frontend/src/hooks/report/useGetReportComments.ts
  frontend/src/hooks/report/useGetReportIdea.ts
  frontend/src/hooks/report/useGetReportOverview.ts
  frontend/src/hooks/report/useGetVideoData.ts
  frontend/src/hooks/report/usePatchReportIdeaBookmark.ts
  frontend/src/hooks/report/usePollReportStatus.ts
  frontend/src/hooks/report/usePostReportByUrl.ts
  frontend/src/pages/main/MainPage.tsx
  frontend/src/pages/main/_components/UrlInputForm.tsx
  frontend/src/pages/main/_components/UrlInputModal.tsx
  frontend/src/pages/main/_components/VideoCard.tsx
  frontend/src/pages/main/_components/VideoRecommendation.tsx
  frontend/src/pages/main/dummy.ts
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/_components/VideoSummary.tsx
  frontend/src/pages/report/_components/analysis/AlgorithmOptimization.tsx
  frontend/src/pages/report/_components/analysis/TabAnalysis.tsx
  frontend/src/pages/report/_components/analysis/ViewerExitAnalysis.tsx
  frontend/src/pages/report/_components/idea/ContentsIdea.tsx
  frontend/src/pages/report/_components/idea/TabIdea.tsx
  frontend/src/pages/report/_components/idea/TrendKeywords.tsx
  frontend/src/pages/report/_components/overview/CommentFeedback.tsx
  frontend/src/pages/report/_components/overview/CommentSkeleton.tsx
  frontend/src/pages/report/_components/overview/Evaluation.tsx
  frontend/src/pages/report/_components/overview/Summary.tsx
  frontend/src/pages/report/_components/overview/TabOverview.tsx
  frontend/src/pages/report/dummy.ts
  frontend/src/router/router.tsx
  frontend/src/types/main.ts
  frontend/src/types/report/all.ts
  frontend/src/types/report/comment.ts
  frontend/src/types/report/new.ts
Labels: ✨Feature

#152 [DEV] 배포 환경 구글 로그인 오류 긴급 수정
  frontend/src/api/axios.ts
Labels: 🐛Bug

#173 [DOCS] 컨벤션 및 타이포그래피 가이드 문서 README 경로 정리
  README.md
  Rules.md
  frontend/src/layouts/_components/navbar/NavbarLink.tsx
  frontend/src/main.tsx
  frontend/src/pages/report/_components/analysis/AlgorithmOptimization.tsx
  frontend/src/pages/report/_components/analysis/ViewerExitAnalysis.tsx
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/pages/setting/_components/ConsentTab.tsx
  frontend/src/pages/setting/_components/ProfileTab.tsx
  frontend/src/pages/setting/_components/SettingButton.tsx
  frontend/src/pages/setting/_components/SettingInput.tsx
  frontend/src/pages/setting/_components/WithdrawlModal.tsx
  frontend/src/styles/Typography.md
  frontend/src/styles/global.css
  frontend/src/styles/typo.css
Labels: 📝Docs

#170 [DEV] 동의 상태를 authStore 기반으로 통합
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/stores/consentStore.ts
  frontend/src/stores/snsFormStore.ts
Labels: ♻️Refactor

#175 [FIX] 계정 전환 시 SNS 정보 초기화되지 않는 오류 수정
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/stores/snsFormStore.ts
Labels: 🐛Bug

#168 [DEV] AccessToken 만료 시 자동 로그아웃 처리
  frontend/src/api/axios.ts
  frontend/src/components/AuthWatcher.tsx
  frontend/src/hooks/useLogout.ts
  frontend/src/layouts/RootLayout.tsx
  frontend/src/pages/auth/GoogleRedirectPage.tsx
  frontend/src/utils/auth.ts
  frontend/src/utils/tokenTimer.ts
Labels: ✨Feature

#188 [DEV] 모바일 사이드바 아이콘 재정렬 및 푸터 외부 링크 연결 수정
  frontend/src/layouts/_components/Footer.tsx
  frontend/src/layouts/_components/navbar/NavbarLinksList.tsx
  frontend/src/layouts/_components/navbar/NavbarMobile.tsx
Labels: ♻️Refactor

#196 [FIX] SettingPage 동의 토글 누르면 불필요한 렌더링 발생 문제 해결
  frontend/src/hooks/setting/useFetchMyProfile.ts
  frontend/src/pages/setting/_containers/ConsentSettings.tsx
  frontend/src/pages/setting/_containers/ProfileSettings.tsx
Labels: 🐛Bug

#200 [DEV] Gemini 자동 리뷰 워크플로우 트리거 조건 수정
  .github/workflows/gemini-pr-review.yml
Labels: 🌏Infra

#198 [DEV] 로그아웃 시 auth-storage 및 sns-form-storage 초기화
  frontend/src/hooks/useLogout.ts
  frontend/src/layouts/_components/navbar/NavbarTablet.tsx
  frontend/src/pages/setting/SettingPage.tsx
  frontend/src/utils/auth.ts
Labels: ♻️Refactor

#199 [DEV] 폴링 로직 전역화 및 리포트 생성 관련 기능 리팩토링
  frontend/src/App.tsx
  frontend/src/components/GlobalReportPoller.tsx
  frontend/src/hooks/report/useDeleteMyReport.ts
  frontend/src/hooks/report/usePollReportStatus.ts
  frontend/src/hooks/report/usePostReportById.ts
  frontend/src/hooks/report/usePostReportByUrl.ts
  frontend/src/layouts/RootLayout.tsx
  frontend/src/layouts/_components/navbar/NavbarLinksList.tsx
  frontend/src/pages/my/_components/myReportModal.tsx
  frontend/src/pages/report/ReportPage.tsx
  frontend/src/pages/report/_components/GeneratingModal.tsx
  frontend/src/pages/report/_components/UpdateModal.tsx
  frontend/src/pages/report/_components/VideoSummary.tsx
  frontend/src/pages/report/_components/analysis/TabAnalysis.tsx
  frontend/src/pages/report/_components/analysis/ViewerExitAnalysis.tsx
  frontend/src/pages/report/_components/idea/ContentsIdea.tsx
  frontend/src/pages/report/_components/idea/TabIdea.tsx
  frontend/src/pages/report/_components/overview/TabOverview.tsx
  frontend/src/stores/reportStore.ts
  frontend/src/types/report/new.ts
  frontend/src/utils/format.ts
Labels: ♻️Refactor, gemini-pr-review
